package com.eventticketing.reservation.domain;

import com.eventticketing.common.domain.BaseEntity;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * A single admission ticket, generated by the backend when a booking is confirmed by payment.
 * Seated bookings produce one ticket per seat (carrying the seat + section); general-admission
 * bookings produce one ticket per purchased quantity (carrying the section only). Every ticket
 * has a unique {@link #ticketNumber}.
 */
@Entity
@Table(name = "ticket")
@Getter
@Setter
@NoArgsConstructor
public class Ticket extends BaseEntity {

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "booking_id", nullable = false)
    private Booking booking;

    @Column(name = "event_id", nullable = false)
    private Long eventId;

    @Column(name = "section_id")
    private Long sectionId;

    @Column(name = "seat_id")
    private Long seatId;

    @Column(name = "ticket_number", nullable = false, length = 48)
    private String ticketNumber;

    @Column(name = "seat_label", length = 16)
    private String seatLabel;

    @Column(name = "section_name", length = 120)
    private String sectionName;
}
